# -*- coding: utf-8 -*-

{
    'name': 'Siddhivinayak ERP',
    'version': '14.0.1.0.0',
    'sequence': 1,
    'summary': """Real Estate Management & Operations""",
    'description': """Real Estate Management""",
    "category": "Industry",
    'author': 'Harshal Bhoir',
    'company': 'Harshal Bhoir',
    'maintainer': 'Harshal Bhoir',
    'website': "https://harshalbhoir.github.io",
    'depends': ['base', 'account', 'contacts', 'l10n_in', 'login_page', 'auto_backup',  'ow_web_responsive',
                'website_disabled', 'odoo-debrand','web_pwa_oca'],
    'license': 'AGPL-3',
    'data': ['security/ir.model.access.csv',
        'security/custom_security.xml',
        'data/res_partner_data.xml',
        'data/res_company_data.xml',
        'wizard/print_payment_summary_view.xml',
        'wizard/aged_partner.xml',
        'views/siddhivinayak_erp_template.xml',
        'views/company_extension_view.xml',
        'views/account_extension_view.xml',
        'views/account_move_extension_view.xml',
        'views/partner_extension_view.xml',
        'report/report_aged_partner.xml',
        'report/report.xml',
        'views/custom_menus.xml',
    ],
    # 'qweb': [
    #     'static/src/xml/siddhivinayak_erp_template.xml',
    # ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
